services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env

  postgres_db:
    image: postgres:17-alpine
    ports:
     - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: